### ISSUE TITLE
Tie::Cycle is not indexed

### ISSUE THREAD

**Issue by eserte** [briandfoy/tie-cycle#3]
Tie::Cycle cannot be found on metacpan anymore.
In a CPAN.pm shell:
```
cpan> m Tie::Cycle
No objects of type Module found for argument Tie::Cycle
```

**Comment by briandfoy** [comment]
Curious. I guess I deleted too much in my recent purge. I've uploaded 1.222. Thanks,

**Comment by chorny** [comment]
Problem is still present.

**Comment by briandfoy** [comment]
I've uploaded 1.224 and received that successful indexing message from PAUSE. Curiously I didn't find a message from PAUSE for 1.222 even though it's there. I'll check back in a couple days to verify it's indexed.

**Comment by briandfoy** [comment]
I've verified that 1.224 shows up in the index. Thanks for reminding me to check.
